import random
words = ["apple", "beach", "brain", "bread", "brush", "chair", "chest", "chord", "click", "clock",
    "cloud", "dance", "diary", "drink", "earth", "feast", "field", "flame", "glass", "grape",
    "green", "heart", "house", "juice", "light", "lemon", "melon", "money", "music", "night",
    "ocean", "paint", "paper", "phone", "piano", "pilot", "plant", "radio", "river", "scene",
    "shirt", "shoes", "smile", "snake", "space", "spoon", "storm", "table", "tiger", "toast",
    "touch", "train", "truck", "voice", "water", "watch", "whale", "world", "write", "youth",
    "zebra", "about", "above", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along",
    "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena", "argue",
    "arise", "armor", "array", "arrow", "aside", "asset", "audio", "audit", "avoid", "award",
    "aware", "awful", "awoke", "bacon", "badge", "badly", "baker", "basic", "basis", "basin",
    "bathe", "beach", "beard", "beast", "begin", "being", "below", "bench", "berry", "birth",
    "black", "blade", "blame", "blank", "blast", "blaze", "bleed", "blend", "blind", "block",
    "blood", "bloom", "blown", "board", "boast", "bonus", "boost", "bound", "bowel", "brain",
    "brake", "brand", "brave", "bread", "break", "breed", "brief", "bring", "brisk", "broad",
    "broke", "brown", "build", "built", "bunch", "burnt", "burst", "buyer", "cabin", "cable",
    "cache", "calmly", "camel", "canal", "candy", "canes", "canon", "cargo", "carry", "carve",
    "casey", "catch", "cause", "cease", "chain", "chair", "chalk", "chaos", "charm", "chart",
    "chase", "cheap", "check", "cheek", "cheer", "chess", "chest", "chews", "chief", "child",
    "chill", "china", "chips", "choir", "chord", "chunk", "cider", "cigar", "circa", "civic",
    "civil", "claim", "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock",
    "close", "cloth", "cloud", "clown", "coach", "coast", "cobra", "codes", "coins", "color",
    "comic", "conch", "couch", "could", "count", "court", "cover", "crack", "craft", "crash",
    "crawl", "crazy", "cream", "creed", "creek", "crest", "cried", "crime", "crisp", "cross",
    "crowd", "crown", "crude", "cruel", "crush", "crust", "crypt", "cubic", "curry", "cycle",
    "daily", "dairy", "dance", "dated", "dealt", "death", "debug", "debut", "delay", "delta",
    "dense", "depth", "derby", "devil", "diary", "digit", "dirty", "ditch", "diver", "dizzy",
    "dogma", "dolls", "donor", "donut", "doubt", "dough", "downy", "dozen", "draft", "drain",
    "drama", "drank", "drawl", "drawn", "dread", "dream", "dress", "dried", "drill", "drink",
    "drive", "drone", "droop", "drove", "drown", "drugs", "drunk", "dryer", "duchy", "ducks",
    "dummy", "dumps", "dunes", "dusty", "dying", "eagle", "early", "earth", "easel", "ebony",
    "edged", "edict", "edify", "eject", "elbow", "elder", "elect", "elegy", "elite", "elope",
    "elude", "email", "embed", "ember", "empty", "enact", "enemy", "enjoy", "enter", "entry",
    "envoy", "epoch", "equal", "equip", "erase", "erect", "error", "erupt", "essay", "ethic",
    "evict", "exact", "exalt", "excel", "exert", "exile", "exist", "extra", "exult", "eying",
    "fable", "facet", "faint", "fairy", "faith", "false", "fancy", "farms", "fatal", "fated",
    "favor", "feast", "fecal", "felon", "femur", "fence", "ferry", "fetch", "fever", "fewer",
    "fiber", "field", "fiery", "fifth", "fifty", "fight", "filed", "files", "fills", "films",
    "filth", "final", "finch", "finds", "finer", "fired", "fires", "first", "fishy", "fixed",
    "fixer", "flail", "flair", "flake", "flame", "flank", "flare", "flash", "flask", "flaty",
    "fleck", "fleet", "flesh", "flies", "fling", "flint", "flips", "float", "flock", "flood",
    "floor", "flora", "flour", "flown", "fluff", "fluid", "fluke", "flume", "flush", "flute",
    "flyer", "focal", "focus", "foggy", "folks", "force", "forge", "forth", "forty", "forum",
    "found", "frame", "fraud", "fresh", "front", "frost", "frown", "fruit", "fully", "funny",
    "gamma", "gates", "gauge", "gaunt", "gears", "gecko", "gelid", "genes", "genie", "genre",
    "ghost", "giant", "gifts", "gills", "gipsy", "girls", "girth", "given", "giver", "glade",
    "glass", "glaze", "gleam", "glean", "glide", "glint", "gloat", "globe", "gloom", "glory",
    "gloss", "glove", "glows", "glued", "gnash", "gnome", "goals", "goats", "godly", "going",
    "golem", "golly", "gonna", "goods", "goose", "gorge", "gourd", "grace", "grade", "graft",
    "grail", "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grate", "grave",
    "gravy", "graze", "great", "greed", "green", "greet", "grief", "grill", "grime", "grimy",
    "grind", "grins", "gripe", "groan", "groom", "gross", "group", "grove", "growl", "grown",
    "gruff", "grunt", "guard", "guess", "guest", "guide", "guild", "guilt", "guise", "gully",
    "habit", "hairy", "halls", "hands", "handy", "hangs", "happy", "hardy", "harsh", "haste",
    "hasty", "hatch", "hater", "haunt", "haven", "havoc", "hazel", "heads", "heady", "heard",
    "heart", "heavy", "hedge", "hefty", "heirs", "hello", "hence", "herbs", "hills", "hinge",
    "hippo", "hippy", "hired", "hitch", "hoard", "hobby", "hoist", "holds", "holes", "holly",
    "homes", "honey", "honor", "hoped", "hopes", "horde", "horns", "horse", "hotel", "hound",
    "hours", "house", "hover", "howdy", "human", "humid", "humor", "humph", "humps", "hurry",
    "hushy", "hydro", "hyena", "hyper", "icons", "ideal", "ideas", "idiom", "idiot", "idols",
    "igloo", "image", "imbue", "impel", "imply", "inane", "index", "indie", "inner", "input",
    "inter", "intro", "ionic", "irate", "irony", "islet", "issue", "itchy", "items", "ivory",
    "jaded", "jails", "japan", "jaunt", "jazzy", "jeans", "jelly", "jerks", "jerky", "jests",
    "jewel", "joint", "jokes", "joker", "jolly", "joust", "joyed", "judge", "juice", "juicy",
    "jumbo", "jumps", "jumpy", "junta", "juror", "kappa", "karma", "kayak", "keeps", "kebab",
    "khaki", "kicks", "kills", "kinds", "kings", "kiosk", "kites", "kitty", "knack", "kneel",
    "knees", "knell", "knife", "knock", "knots", "known", "knows", "koala", "label", "labor",
    "laced", "laces", "lacks", "laden", "ladle", "lager", "lakes", "lamps", "lance", "lands",
    "lanes", "large", "larva", "laser", "lasso", "lasts", "latch", "later", "latex", "lathe",
    "laugh", "layer", "leads", "leafy", "leaks", "leaky", "leans", "leapt", "learn", "lease",
    "leash", "least", "leave", "ledge", "leech", "leery", "lefty", "legal", "lemon", "lemur",
    "lends", "level", "lever", "licks", "light", "liked", "liken", "likes", "lilac", "limbo",
    "limit", "lined", "linen", "liner", "lines", "lingo", "links", "lions", "lists", "lived",
    "liven", "liver", "lives", "llama", "loads", "loans", "loath", "local", "locks", "locus",
    "lodge", "lofty", "logic", "login", "logos", "loner", "loose", "lords", "lorry", "loser",
    "loses", "lotto", "lotus", "lover", "loves", "lower", "loyal", "lucid", "lucky", "lulls",
    "lumps", "lumpy", "lunar", "lunch", "lunge", "lungs", "lurch", "lured", "lusty", "lying",
    "lymph", "lyric", "macho", "macro", "madam", "magic", "magma", "maids", "mails", "major",
    "maker", "makes", "males", "mamma", "manga", "mange", "mango", "mangy", "mania", "manic",
    "manor", "maple", "march", "marry", "marsh", "masks", "mason", "match", "mates", "matte",
    "maybe", "mayor", "meals", "mealy", "means", "meant", "meats", "medal", "media", "medic",
    "meets", "melee", "melon", "melts", "memos", "mercy", "merge", "merit", "merry", "metal",
    "meter", "metro", "micro", "midst", "might", "miles", "milky", "mills", "mimic", "mince",
    "minds", "mined", "miner", "mines", "minor", "minus", "mirth", "miser", "misty", "mixed",
    "mixer", "mixes", "model", "modem", "modes", "moist", "molar", "molds", "moldy", "moles",
    "money", "month", "moody", "moons", "moose", "moral", "moron", "morph", "mossy", "motel",
    "motif", "motor", "motto", "mould", "mound", "mount", "mourn", "mouse", "mouth", "moved",
    "mover", "moves", "movie", "mower", "mucky", "mucus", "muddy", "mules", "multi", "mummy",
    "mumps", "munch", "mural", "mused", "mushy", "music", "musky", "musty", "muted", "muted",
    "myths", "nadir", "nails", "naive", "naked", "named", "names", "nanny", "nasal", "nasty",
    "natal", "naval", "navel", "needs", "needy", "neighbor", "nerve", "never", "newer", "newly",
    "nicer", "niche", "niece", "night", "ninja", "ninth", "noble", "nobly", "nodal", "noise",
    "noisy", "nomad", "noose", "north", "nosey", "notch", "noted", "notes", "novel", "nurse",
    "nutty", "nylon", "nymph", "oaken", "oases", "oasis", "ocean", "ochre", "octal", "octet",
    "odder", "oddly", "offal", "offer", "often", "oiled", "olden", "older", "olive", "omega",
    "onion", "onset", "opera", "opine", "opium", "optic", "orbit", "order", "organ", "other",
    "otter", "ought", "ounce", "outer", "ovary", "ovate", "overt", "owned", "owner", "oxide",
    "ozone", "pacer", "paddy", "padre", "pagan", "pager", "paint", "pales", "palms", "palsy",
    "panel", "panic", "pansy", "pants", "papal", "paper", "parer", "parka", "parks", "parry",
    "parse", "parts", "party", "pasta", "paste", "pasty", "patch", "patio", "patsy", "patty",
    "pause", "paved", "pawed", "payed", "payer", "peace", "peach", "pearl", "pecan", "pedal",
    "pelle", "penal", "pence", "penis", "penny", "perch", "peril", "perks", "perky", "pesky",
    "pests", "petal", "petty", "phase", "phone", "phony", "photo", "piano", "picks", "picky",
    "piece", "piety", "piggy", "pikes", "piled", "piles", "pilot", "pinch", "pined", "pines",
    "pinky", "pinto", "pious", "pipes", "pique", "pitch", "pithy", "pivot", "pixel", "pixie",
    "place", "plaid", "plain", "plait", "plane", "plank", "plant", "plate", "plaza", "plead",
    "pleat", "plied", "plier", "plops", "plots", "pluck", "plugs", "plumb", "plume", "plump",
    "plums", "plush", "poems", "poesy", "point", "poise", "poker", "polar", "polka", "polls",
    "polyp", "ponds", "pooch", "poppy", "porch", "pores", "ports", "posed", "poser", "poses",
    "posit", "posse", "posts", "pouch", "pound", "power", "prank", "prawn", "prays", "preen",
    "press", "price", "prick", "pride", "pried", "prime", "primp", "print", "prior", "prism",
    "privy", "prize", "probe", "promo", "prone", "prong", "proof", "prose", "proud", "prove",
    "prowl", "proxy", "prude", "prune", "psalm", "pubic", "pudgy", "puffy", "pulls", "pulpy",
    "pulse", "pumps", "punch", "puppy", "purge", "purse", "pushy", "putty", "pygmy", "quack",
    "quake", "qualm", "quark", "quart", "quash", "quasi", "queen", "queer", "quell", "query",
    "quest", "queue", "quick", "quiet", "quill", "quilt", "quirk", "quite", "quota", "quote",
    "quoth", "rabbi", "rabid", "racer", "races", "radar", "radii", "radio", "rafts", "raged",
    "rages", "rainy", "raise", "rally", "ralph", "ramen", "ranch", "range", "rapid", "rarer",
    "raspy", "rated", "rates", "ratio", "ratty", "raven", "razor", "reach", "react", "ready",
    "realm", "rearm", "rears", "rebel", "rebus", "recap", "recur", "reeds", "reedy", "refer",
    "refit", "regal", "rehab", "reign", "relax", "relay", "relic", "remit", "remix", "renal",
    "renew", "repay", "repel", "reply", "rerun", "reset", "resin", "retch", "retro", "retry",
    "revel", "revue", "rhino", "rhyme", "rider", "rides", "ridge", "rifle", "right", "rigid",
    "rigor", "rinse", "ripen", "riper", "risen", "riser", "rises", "risks", "risky", "rival",
    "river", "rivet", "roach", "roads", "roady", "roams", "roans", "roars", "roast", "robbe",
    "robot", "rocks", "rocky", "rodeo", "roger", "rogue", "roles", "roman", "roofs", "rooms",
    "roomy", "roost", "roots", "roped", "ropes", "roses", "rotor", "rough", "round", "rouse",
    "route", "rover", "rowdy", "rowed", "royal", "ruler", "rules", "rumba", "rumor", "runes",
    "rungs", "runny", "rural", "rusty", "saber", "sable", "sacks", "sadly", "safer", "safes",
    "saint", "salad", "sales", "sally", "salon", "salsa", "salts", "salty", "salve", "salvo",
    "sandy", "saner", "sappy", "sassy", "satin", "satyr", "sauce", "saucy", "sauna", "saute",
    "saved", "saver", "saves", "savor", "savvy", "scald", "scale", "scalp", "scaly", "scamp",
    "scant", "scare", "scarf", "scary", "scene", "scent", "scion", "scoff", "scold", "scoop",
    "scope", "score", "scorn", "scour", "scout", "scowl", "scram", "scrap", "scree", "screw",
    "scrub", "scrum", "scuba", "sedan", "seeds", "seedy", "segue", "seize", "sells", "semen",
    "semis", "sends", "sense", "sepia", "serif", "serum", "serve", "setup", "seven", "sever",
    "sewer", "shack", "shade", "shady", "shaft", "shake", "shaky", "shale", "shall", "shalt",
    "shame", "shamp", "shape", "shard", "share", "shark", "sharp", "shave", "shawl", "sheaf",
    "shear", "sheed", "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine", "shiny",
    "ships", "shire", "shirk", "shirt", "shook", "shock", "shoes", "shone", "shook", "shoot",
    "shore", "shorn", "short", "shout", "shove", "shown", "shows", "showy", "shred", "shrew",
    "shrub", "shrug", "shuck", "shunt", "shush", "shuts", "shyly", "sides", "siege", "sieve",
    "sight", "sigma", "signs", "silky", "silly", "since", "sinew", "singe", "sings", "sinus",
    "siren", "sissy", "sites", "sixth", "sixty", "sized", "sizes", "skate", "skier", "skies",
    "skiff", "skill", "skimp", "skirt", "skulk", "skull", "skunk", "slack", "slain", "slang",
    "slant", "slash", "slate", "slave", "sleek", "sleep", "sleet", "slept", "slice", "slick",
    "slide", "slime", "slimy", "sling", "slink", "sloop", "slope", "slosh", "sloth", "slump",
    "slung", "slurp", "slush", "slyly", "smack", "small", "smart", "smash", "smear", "smell",
    "smelt", "smile", "smirk", "smite", "smith", "smock", "smoke", "smoky", "smote", "snack",
    "snafu", "snail", "snake", "snaky", "snare", "snarl", "sneak", "sneer", "snide", "sniff",
    "snipe", "snoop", "snore", "snort", "snout", "snowy", "snuck", "snuff", "soapy", "sober",
    "solar", "solid", "solve", "sonar", "sonic", "sooth", "sooty", "sorry", "sound", "south",
    "space", "spade", "spank", "spare", "spark", "spasm", "spawn", "speak", "spear", "speck",
    "speed", "spell", "spelt", "spend", "spent", "sperm", "spice", "spicy", "spied", "spiel",
    "spike", "spiky", "spill", "spilt", "spine", "spiny", "spire", "spite", "splat", "split",
    "spoil", "spoke", "spoof", "spook", "spool", "spoon", "spore", "sport", "spout", "spray",
    "spree", "sprig", "spunk", "spurn", "spurt", "squad", "squat", "squib", "stack", "staff",
    "stage", "staid", "stain", "stair", "stake", "stale", "stalk", "stall", "stamp", "stand",
    "stank", "stare", "stark", "start", "stash", "state", "stave", "stays", "stead", "steak",
    "steal", "steam", "steed", "steel", "steep", "steer", "stein", "stern", "stick", "stiff",
    "still", "stilt", "sting", "stink", "stint", "stock", "stoic", "stoke", "stole", "stomp",
    "stone", "stony", "stood", "stool", "stoop", "store", "stork", "storm", "story", "stout",
    "stove", "strap", "straw", "stray", "strip", "strut", "stuck", "study", "stuff", "stump",
    "stung", "stunt", "style", "styli", "suave", "sugar", "suite", "suits", "sulky", "sully",
    "sumac", "sunny", "super", "surer", "surge", "surly", "sushi", "swami", "swamp", "swank",
    "swarm", "swash", "swath", "swear", "sweat", "sweep", "sweet", "swell", "swept", "swift",
    "swill", "swine", "swing", "swirl", "swish", "swoon", "swoop", "sword", "swore", "sworn",
    "swung", "synod", "syrup", "table", "taboo", "tacit", "tacky", "taffy", "taint", "taken",
    "taker", "takes", "tales", "talks", "tally", "talon", "tamer", "tango", "tangy", "tanks",
    "taper", "tapir", "tardy", "tarot", "taste", "tasty", "tater", "taunt", "tawny", "taxes",
    "teach", "teary", "tease", "teddy", "teeth", "tempo", "tenet", "tenor", "tense", "tenth",
    "tepee", "tepid", "terra", "terse", "tests", "testy", "texts", "thank", "theft", "their",
    "theme", "there", "these", "theta", "thick", "thief", "thigh", "thing", "think", "third",
    "thong", "thorn", "those", "three", "threw", "throb", "throw", "thrum", "thumb", "thump",
    "thyme", "tiara", "tibia", "tidal", "tiger", "tight", "tilde", "timer", "times", "timid",
    "tipsy", "titan", "tithe", "title", "toast", "today", "token", "tonal", "toner", "tones",
    "topic", "torch", "torso", "total", "totem", "touch", "tough", "towel", "tower", "towns",
    "toxic", "toxin", "trace", "track", "tract", "trade", "trail", "train", "trait", "tramp",
    "trash", "trawl", "tread", "treat", "trees", "trend", "triad", "trial", "tribe", "trice",
    "trick", "tried", "tries", "tripe", "trite", "troll", "troop", "trope", "trout", "trove",
    "truce", "truck", "truer", "truly", "trump", "trunk", "truss", "trust", "truth", "tryst",
    "tuber", "tubes", "tulip", "tulle", "tumor", "tunic", "turbo", "tutor", "twang", "tweak",
    "tweed", "tweet", "twice", "twine", "twins", "twirl", "twist", "tying", "typed", "types",
    "uncle", "under", "undue", "unfit", "union", "unite", "unity", "unlit", "unmet", "unset",
    "untie", "until", "unzip", "upend", "upped", "upper", "upset", "urban", "urine", "usage",
    "users", "usher", "using", "usual", "usurp", "utter", "vague", "valet", "valid", "valor",
    "value", "valve", "vapor", "vases", "vault", "vaunt", "vegan", "venom", "venue", "verge",
    "verse", "verso", "verve", "vicar", "video", "vigil", "vigor", "villa", "vinyl", "viola",
    "viper", "viral", "virus", "visit", "visor", "vista", "vital", "vivid", "vixen", "vocal",
    "vodka", "vogue", "voice", "voila", "vomit", "voter", "vouch", "vowel", "vying", "wacky",
    "wafer", "wager", "wages", "wagon", "waist", "waive", "waked", "waken", "wakes", "waltz",
    "waste", "watch", "water", "waver", "waxed", "weary", "weave", "wedge", "weeds", "weedy",
    "weeks", "weigh", "weird", "welch", "wells", "whack", "whale", "wharf", "wheat", "wheel",
    "whelp", "where", "which", "whiff", "while", "whine", "whiny", "whirl", "whisk", "white",
    "whole", "whoop", "whose", "widen", "wider", "widow", "width", "wield", "wight", "willy",
    "wince", "winch", "winds", "windy", "wings", "wired", "wires", "wiser", "wispy", "witch",
    "witty", "woman", "women", "woods", "woody", "wooer", "words", "wordy", "works", "world",
    "worms", "worry", "worse", "worst", "worth", "would", "wound", "woven", "wreck", "wrist",
    "write", "wrong", "wrote", "wrung", "yacht", "yards", "yearn", "years", "yeast", "yield",
    "young", "youth", "yummy", "zebra", "zesty", "zones", "zooms"
]

print("YOU HAVE ONLY 5 CHANCES TO GUESS THE WORD......")
print("-----INSTRUCTIONS-----")
print("AFTER EACH WORD YOU ENTER THERE IS A OUTPUT ACC. TO YOUR WORD")
print("*-> Indicates you entered right letter on right place")
print("#-> Indicates you have entered right letter but on wrong place")
print("^-> Indicates you have entered wrong letter it does not appear in word")
gen=random.choice(words)

def wordle():
    for  x in u_word:
        if(x in gen and u_word.index(x)==gen.index(x)):
            print('*',end='')
        elif(x in gen):
            print('#',end='')
        else:
            print('-',end='')
    print()

for i in range(5):
    u_word=input("enter 5 letter word:")
    if(u_word==gen):
        print("Right Guess\n",u_word)
        break
    if(len(u_word)!=5):
        print("Enter only 5 letter words.....")
        break
    wordle()